### PR TITLE
Emit structured info for variables which aren't fields as well

### PR DESCRIPTION
**Pull request by theres-waldo**

### CODE REVIEW

**Comment by theres-waldo** [comment]
For some context, this is the next PR in a series to expand the set of symbols for which the C++ indexer generates structured analysis records. Previous PRs in this series were #766, #779, and #786.

I've been testing these changes together with WIP changes to leverage the structured analysis info to annotate tokens with a semantic token kind, for semantic highlighting purposes. My current WIP plumbs this as far as new classnames in the generated HTML (e.g. `syn_parameter`), which I've been visualizing for testing purposes with a Stylus userstyle. For reference, I've uploaded these WIP patches [here](https://github.com/theres-waldo/mozsearch/pull/1).

My current plan is to continue with the indexer changes until all the major categories of symbols are covered (some remaining ones on my todo list are namespaces, and class/function templates), and then proceed with trying to get my semantic highlighting changes into a landable state. I'm open to doing this in a different order (e.g. get the semantic highlighting plumbing landed first, and then onboard additional symbol types) if you prefer.

**Comment by asutherland** [comment]
@theres-waldo I'm interested to understand what this potentially does to the size of our `target.mozsearch-index.zip` artifacts (and the extracted size).  Can you do a try-run against m-c so we can compare?  I don't think this would change whether we want the changes (we do), but might impact indexer resources and/or taskcluster job expiration dates.

> My current plan is to continue with the indexer changes until all the major categories of symbols are covered (some remaining ones on my todo list are namespaces, and class/function templates), and then proceed with trying to get my semantic highlighting changes into a landable state. I'm open to doing this in a different order (e.g. get the semantic highlighting plumbing landed first, and then onboard additional symbol types) if you prefer.

This sounds good and likely the right order since it will be easier for UX iteration when the data is already present and ideally good, etc.

**Comment by theres-waldo** [comment]
> I'm interested to understand what this potentially does to the size of our `target.mozsearch-index.zip` artifacts (and the extracted size). Can you do a try-run against m-c so we can compare? I don't think this would change whether we want the changes (we do), but might impact indexer resources and/or taskcluster job expiration dates.

Try run: https://treeherder.mozilla.org/jobs?repo=try&revision=08bd9f098db848b163c2640b493e76ba0c40b476

Looking at the Linux indexer job as an example, the size of the `target.mozsearch-index.zip` is 788M, and the extracted size as reported by `unzip -l` is 12G.

I assume we can get a baseline number from somewhere without having to do a dedicated Try push for that?

**Comment by asutherland** [comment]
Yeah, the jobs can be found via https://treeherder.mozilla.org/jobs?repo=mozilla-central&searchStr=searchfox.  [This linux run](https://treeherder.mozilla.org/jobs?repo=mozilla-central&searchStr=searchfox&selectedTaskRun=aD05fvP-TOOBifCSNk9i1Q.0) is 763MiB zipped to your 788MiB zipped and like 300MB more unzipped.  So that's fine, or even more than fine.  Shockingly fine?

**Review by asutherland — APPROVED** [review]
Please make sure to rebase against tip and re-run `make build-test-repo` to get the clang-plugin changes and then `make review-test-repo` to make sure the checks are up to date given the conflict.

**Comment by theres-waldo** [comment]
Rebased and resolved conflicts.

**Pull request merged**
