### PR TITLE
Update IPDL parser.

### PR DESCRIPTION
**Pull request by amccreight**
I haven't actually tried to run it, but I did manage to build the tools/ directory.

### CODE REVIEW

**Comment by staktrace** [comment]
I kicked off a test run to make sure nothing broke

**Comment by amccreight** [comment]
Great. It would also be good to check that eg https://searchfox.org/mozilla-central/source/dom/ipc/PContent.ipdl actually contains links to things. :)

**Comment by staktrace** [comment]
I deployed it to https://kats.searchfox.org/mozilla-central/source/dom/ipc/PContent.ipdl but that file doesn't seem to have links to things. In the index-log I see this:

```
+ xargs /home/ubuntu/mozsearch/tools/target/release/ipdl-analyze -I accessible/ipc/other -I devtools/shared/heapsnapshot -I dom/broadcastchannel -I dom/cache -I dom/clients/manager -I dom/fetch -I dom/file/ipc -I dom/filehandle -I dom/filesystem -I dom/gamepad/ipc -I dom/indexedDB -I dom/ipc -I dom/localstorage -I dom/media/gmp -I dom/media/ipc -I dom/media/systemservices -I dom/media/webrtc -I dom/media/webspeech/synth/ipc -I dom/messagechannel -I dom/midi -I dom/network -I dom/payments/ipc -I dom/plugins/ipc -I dom/presentation/ipc -I dom/quota -I dom/reporting -I dom/serviceworkers -I dom/simpledb -I dom/storage -I dom/webauthn -I dom/webbrowserpersist -I dom/workers/remoteworkers -I dom/workers/sharedworkers -I extensions/spellcheck/hunspell/glue -I gfx/ipc -I gfx/layers/ipc -I gfx/vr/ipc -I hal/sandbox -I ipc/glue -I ipc/testshell -I js/ipc -I js/xpconnect/loader -I layout/base -I layout/ipc -I layout/printing/ipc -I media/mtransport/ipc -I netwerk/cookie -I netwerk/dns -I netwerk/ipc -I netwerk/protocol/ftp -I netwerk/protocol/http -I netwerk/protocol/websocket -I security/manager/ssl -I security/sandbox/win/src/remotesandboxbroker -I toolkit/components/backgroundhangmonitor -I toolkit/components/extensions/webrequest -I toolkit/components/printingui/ipc -I tools/profiler/gecko -I uriloader/exthandler -I uriloader/prefetch -I widget -I widget/gtk -I widget/headless -d /index/mozilla-central/analysis/__GENERATED__/ipc/ipdl/_ipdlheaders -b /index/mozilla-central/gecko-dev -a /index/mozilla-central/analysis
Parsing file /index/mozilla-central/gecko-dev/accessible/ipc/other/PDocAccessible.ipdl
Parsing file /index/mozilla-central/gecko-dev/devtools/shared/heapsnapshot/PHeapSnapshotTempFileHelper.ipdl
Parsing file /index/mozilla-central/gecko-dev/dom/broadcastchannel/PBroadcastChannel.ipdl
Parsing file /index/mozilla-central/gecko-dev/dom/cache/CacheTypes.ipdlh
... (more files omitted)
Parsing file /index/mozilla-central/gecko-dev/dom/media/systemservices/PMediaSystemResourceManager.ipdl
Parsing file /index/mozilla-central/gecko-dev/dom/media/webrtc/PMediaTransport.ipdl
/index/mozilla-central/gecko-dev/dom/media/webrtc/PMediaTransport.ipdl :/index/mozilla-central/gecko-dev/dom/media/webrtc/PMediaTransport.ipdl 7:0 Unexpected token.
Specification could not be parsed.
+ popd
```

So it looks like it hit a parsing error and bailed out

**Comment by staktrace** [comment]
Also it would be good if the ipdl parser emitted a `warn!` when it encounters errors, that way we'll get emails about failures when stuff breaks rather than it just silently failing. (We'll have to invoke it with RUST_LOG=warn but that's easy enough)

**Comment by amccreight** [comment]
Thanks! Yeah, I should change it so that it just warns on errors but doesn't bail out, if I can do that. I think the issue there is that PMediaTransport.ipdl is pre-processed, so I'd need to grab the version out of the objdir or something gross like that. That may require some finagling, so maybe in the short term I'll just have it ignore errors.

Anyways, this should still be okay to merge, because we're just failing at a different place, and it isn't really a bug with the parser.

**Comment by staktrace** [comment]
Yup, makes sense. I'm happy to merge this since it doesn't break anything new :)

**Comment by staktrace** [comment]
The post-processed PMediaTransport.ipdl file doesn't end up in the set of "generated" files that we export via taskcluster to the indexer, unfortunately:

```
~/index/mozilla-central/objdir$ find . -name "PMediaTransport*"
./ipc/ipdl/_ipdlheaders/mozilla/dom/PMediaTransportParent.h
./ipc/ipdl/_ipdlheaders/mozilla/dom/PMediaTransportChild.h
./ipc/ipdl/_ipdlheaders/mozilla/dom/PMediaTransport.h
./ipc/ipdl/PMediaTransportParent.cpp
./ipc/ipdl/PMediaTransportChild.cpp
./ipc/ipdl/PMediaTransport.cpp
```

So if we can just skip over files like that it might be easiest in the short term. Or we can try and export the post-processed file to the indexer. Or just export the `#define`d values somewhere and do the post-processing on the indexer.

**Comment by amccreight** [comment]
Yeah, this is a bit of a mess. It looks like all this file even uses the
preprocessor for is an #ifdef for WebRTC...

**Comment by staktrace** [comment]
Apparently bug 1500228 will expose config.status as an artifact so we might be able to use that to pick out the defines.

**Pull request merged**
