### PR TITLE
Bug 1904474 - Miscellaneous fixes

### PR DESCRIPTION
**Pull request by staktrace**
A few fixes towards bug 1904474. I don't have it fully working yet though.

### CODE REVIEW

**Review by asutherland — APPROVED** [review]
There's no `&>`?  Noooooo

**Comment by staktrace** [comment]
> There's no `&>`? Noooooo

The new thing is like a superset of `&>`

**Comment by asutherland** [comment]
Sorry, I meant `|&` but 

> > There's no `&>`? Noooooo
> 
> The new thing is like a superset of `&>`

Sorry, I meant `|&` but mainly was assuming the mac didn't have it.

**Comment by staktrace** [comment]
I'm not sure what `|&` does. I just tried it in a bash script and got a syntax error. That being said if it's a bash thing it shouldn't matter if it's linux or mac.

**Comment by asutherland** [comment]
https://www.gnu.org/software/bash/manual/html_node/Pipelines.html says:

> If ‘|&’ is used, command1’s standard error, in addition to its standard output, is connected to command2’s standard input through the pipe; it is shorthand for 2>&1 |. This implicit redirection of the standard error to the standard output is performed after any redirections specified by command1.

**Comment by asutherland** [comment]
Note I'm not saying to change anything, just I always struggle to find actual docs on bash that are linkable and so that was nice to find and so I'm linking it here.

**Pull request merged**
