### PR TITLE
Dark mode: Use a brighter color for context.

### PR DESCRIPTION
**Pull request by emilio**

### CODE REVIEW

**Comment by emilio** [comment]
@mystor does this color work for you?

**Review by asutherland — APPROVED** [review]

**Comment by mystor** [comment]
Yeah, manually switching the colour over locally that seems nicer. Might also be worth changing the `.result-upsearch` colour?

**Comment by emilio** [comment]
@mystor already done in https://github.com/mozsearch/mozsearch/pull/475 :)

**Comment by mystor** [comment]
nice :-)

**Pull request merged**
