### PR TITLE
Add a "copy to clipboard" button to (some) panel entries.

### PR DESCRIPTION
**Pull request by emilio**
More explicit alternative to #368.

### CODE REVIEW

**Review by staktrace — APPROVED** [review]
The code looks fine to me. Is it deployed anywhere I can try it out?

**Review by asutherland — APPROVED** [review]
I tested this locally with `make build-searchfox-repo` and it seems great!  Love the generalization so that this can be used on many different panel links!

It would probably be good to sanity check with a run against mozilla-central before landing/shipping just to sanity check.  I'll see if one of us is triggering a run on matrix.

**Comment by asutherland** [comment]
Forgot to mention that I particularly appreciate the attention-to-detail in having the checkmark copy confirmation!

**Comment by staktrace** [comment]
So it's up on dev.searchfox.org now (thanks @asuth!) and I noticed that if I click on the icon for the permalink, it just copies it to the clipboard. But if I click on the icon for e.g. the log or raw links, it **also** navigates to the link after copying. It's not clear to me why the behaviour is different for the permalink link vs the other ones.

**Comment by emilio** [comment]
> So it's up on dev.searchfox.org now (thanks @asuth!) and I noticed that if I click on the icon for the permalink, it just copies it to the clipboard. But if I click on the icon for e.g. the log or raw links, it also navigates to the link after copying. It's not clear to me why the behaviour is different for the permalink link vs the other ones.

Yup, noticed that too, that's because the permalink is handled in JS. Added a patch that should address that (and live-edited the server so if you shift-reload you should see that fixed).

**Comment by emilio** [comment]
(Assuming that with that fixed there's no objection to this)

**Pull request merged**
