### PR TITLE
Bug 1833272 - Handle templated heuristic results in VisitCXXDependentScopeMemberExpr

### PR DESCRIPTION
**Pull request by theres-waldo**

### CODE REVIEW

**Comment by theres-waldo** [comment]
(I did not expect this to be an effective one-liner, but it turned out to be.)

**Review by asutherland — APPROVED** [review]
Ha, yeah (in regards to the 1-liner).  It's definitely shocking to me how often seemingly complex things in the clang space are really just a question of understanding the right Decl type to use and what helper method to call once you have it[1]!

Also, woo!

1: Which really underscores the utility of the AST dumps and how making it easier to go from some existing code to an AST dump excerpt could be useful.  Especially if the dump could also include QualType extracts.  (My most recent foolishness was a failure to call `getPointeeType`.)

**Comment by theres-waldo** [comment]
> making it easier to go from some existing code to an AST dump excerpt could be useful.

With vscode + clangd, you can select some code and run the vscode command `clangd: Show AST`, and vscode will show you the clang AST for the selected code in a tree view.

For example, here I'm selecting a statement:

image

and here is the tree view of the corresponding AST:

image

**Comment by theres-waldo** [comment]
This branch is now deployed to dev.searchfox.org

**Comment by asutherland** [comment]
> With vscode + clangd, you can select some code and run the vscode command `clangd: Show AST`, and vscode will show you the clang AST for the selected code in a tree view.

Holy cow, that's amazing, particularly the scoping to the selection!  Thanks for letting me know about that and taking the time to provide the screenshots!

**Pull request merged**
